export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST'
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS'
export const ADD_ADDRESS_FAIL = 'ADD_ADDRESS_FAIL'

export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST'
export const GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL'
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'