export const ORDER_PLACE_REQUEST = 'ORDER_PLACE_REQUEST'
export const ORDER_PLACE_SUCCESS = 'ORDER_PLACE_SUCCESS'
export const ORDER_PLACE_FAIL = 'ORDER_PLACE_FAIL'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'
