export const SEND_OTP_REQUEST = 'OTP_REQUEST'
export const SEND_OTP_SUCCESS = 'OTP_SUCCESS'
export const SEND_OTP_FAIL = 'OTP_FAIL'

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST'
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS'
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
